### ISSUE TITLE
consider a license change

### ISSUE THREAD

**Issue by metajack** [adjivas/signal#1]
Would you consider changing the license at all? Servo in would like to use this, but the GPL v3 is not MPL-compatible. As most Rust code living in crates.io seems to be dual MIT and Apache 2.0, I would recommend those options.

**Comment by metajack** [comment]
cc @jdm @ms2ger

**Comment by adjivas** [comment]
@metajack I agree your recommendation for [sig](https://github.com/adjivas/sig)'s project. The license is now a dual MIT and Apache 2.0 for Crates.io and Github repository.

**Comment by metajack** [comment]
@adjivas Thank you very much!
